load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "tox_bin",
    #strip_prefix = "rules_python-{}".format(rules_python_version),
    url = "https://github.com/tox-dev/tox/archive/refs/tags/4.0.0a10.zip,
)